name: gestion_laboratorios
services:
  backend:
    build:
      context: C:\Users\BryanS\Desktop\gestion_laboratorios\Backend
      dockerfile: Dockerfile
    container_name: backend_lab_api
    depends_on:
      mongodb:
        condition: service_started
        required: true
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/gestion_laboratorios?authSource=admin
      PORT: "5000"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: C:\Users\BryanS\Desktop\gestion_laboratorios\Backend
        target: /app
        bind:
          create_host_path: true
      - type: volume
        target: /app/node_modules
        volume: {}
  mongo-express:
    container_name: mongo_gui
    depends_on:
      mongodb:
        condition: service_started
        required: true
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
    image: mongo-express
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8081
        published: "8081"
        protocol: tcp
    restart: always
  mongodb:
    container_name: mongo_lab_db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_ROOT_USERNAME: admin
    image: mongo:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 27017
        published: "27017"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
        volume: {}
networks:
  default:
    name: gestion_laboratorios_default
volumes:
  mongo_data:
    name: gestion_laboratorios_mongo_data
